#!/bin/bash
function traverse() {
  for file in $(ls -a "$1")
  do
    #a = `echo "${1}" | awk -F "/" '{print $NF}'`
    if [[ $file = "." ]] || [[ $file = ".." ]]; then
      true
    elif [[ ! -d ${1}/${file} ]]; then
      echo "${1}/${file} [`ls -la ${1}/${file} | awk '{print $5}'`]"
    else
      traverse "${1}/${file}"
    fi
  done
}

traverse "$1"
